apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: component-sample
  namespace: test
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: application-sample
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: component-sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: component-sample-
      labels:
        build.appstudio.openshift.io/application: application-sample
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: component-sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: test
    spec:
      params:
      - name: git-url
        value: https://github.com/mmorhun-org/devfile-sample-code-with-quarkus
      - name: output-image
        value: docker.io/mm4eche/foobar:dev-code-with-quarkus-$(tt.params.git-revision)
      - name: dockerfile
        value: src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:861e28f4eb2380fd1531ee30a9e74fb6ce496b9f
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: component-sample/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
